name: Docs
on:
  push:
    branches:
      - main
jobs:
  docs:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: install_pandoc
        run: sudo apt-get install pandoc
      - id: deployment
        uses: sphinx-notes/pages@v3
        with:
          publish: false
      # - uses: actions/checkout@v3
      # - uses: actions/setup-python@v3
      # - name: Install dependencies
        # run: |
          # python3 -m pip install sphinx furo
          # python3 -m pip install --no-deps --ignore-requires-python nb-sphinx myst-parser
      # - name: Sphinx build
       # run: |
         # sphinx-build doc _build
      # - name: Deploy
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          # publish_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.deployment.outputs.artifact }}
          force_orphan: true
